<a href="https://colab.research.google.com/github/ViniciusCesarSena/Data_learning/blob/main/DataAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#1 passo: conectar google colab ao drive

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
#2 passo: importar base de dados do google Drive
caminho_arquivo = '/content/drive/MyDrive/Customer_support_data.csv'

#3 passo: Faze limpeza na base de dados
import pandas as pd

#4 passo: Carregar a base de dados
try:
  df = pd.read_csv(caminho_arquivo)
  df1= df.copy()


  #se ocorrer um erro do tipo 'ParserError' ParserError durante a leitura do arquivo CSV, o bloco de código seguinte será executado.
  #bloco except é útil para lidar com possíveis problemas de formato no arquivo de entrada.
except pd.errors.ParserError:
  print("Erro ao ler o arquivo CSV.Verificar formato do arquivo")

In [3]:
print(f"A quantidade de linhas e colunas da tabela, respectivamente é: {df.shape}")

A quantidade de linhas e colunas da tabela, respectivamente é: (85907, 20)

In [4]:
#mostra as linhas iniciais da tabela (uma prévia)

df1.head()

,Unique id,channel_name,category,Sub-category,Customer Remarks,Order_id,order_date_time,Issue_reported at,issue_responded,Survey_response_Date,Customer_City,Product_category,Item_price,connected_handling_time,Agent_name,Supervisor,Manager,Tenure Bucket,Agent Shift,CSAT Score
0,7e9ae164-6a8b-4521-a2d4-58f7c9fff13f,Outcall,Product Queries,Life Insurance,NaN,c27c9bb4-fa36-4140-9f1f-21009254ffdb,NaN,01/08/2023 11:13,01/08/2023 11:47,01-Aug-23,NaN,NaN,NaN,NaN,Richard Buchanan,Mason Gupta,Jennifer Nguyen,On Job Training,Morning,5
1,b07ec1b0-f376-43b6-86df-ec03da3b2e16,Outcall,Product Queries,Product Specific Information,NaN,d406b0c7-ce17-4654-b9de-f08d421254bd,NaN,01/08/2023 12:52,01/08/2023 12:54,01-Aug-23,NaN,NaN,NaN,NaN,Vicki Collins,Dylan Kim,Michael Lee,>90,Morning,5
2,200814dd-27c7-4149-ba2b-bd3af3092880,Inbound,Order Related,Installation/demo,NaN,c273368d-b961-44cb-beaf-62d6fd6c00d5,NaN,01/08/2023 20:16,01/08/2023 20:38,01-Aug-23,NaN,NaN,NaN,NaN,Duane Norman,Jackson Park,William Kim,On Job Training,Evening,5
3,eb0d3e53-c1ca-42d3-8486-e42c8d622135,Inbound,Returns,Reverse Pickup Enquiry,NaN,5aed0059-55a4-4ec6-bb54-97942092020a,NaN,01/08/2023 20:56,01/08/2023 21:16,01-Aug-23,NaN,NaN,NaN,NaN,Patrick Flores,Olivia Wang,John Smith,>90,Evening,5
4,ba903143-1e54-406c-b969-46c52f92e5df,Inbound,Cancellation,Not Needed,NaN,e8bed5a9-6933-4aff-9dc6-ccefd7dcde59,NaN,01/08/2023 10:30,01/08/2023 10:32,01-Aug-23,NaN,NaN,NaN,NaN,Christopher Sanchez,Austin Johnson,Michael Lee,0-30,Morning,5

# Analisando o período de dados coletados:

este código  avalia o período de dados coletados em um DataFrame df1, desde o primeiro report até o último, utilizando as seguintes etapas:

Extrair datas:

`pd.to_datetime(df1['Issue_reported at']).dt.date.min()`:

Converte a coluna Issue_reported at para o tipo datetime e extrai a data (sem hora) do primeiro report. (o valor mínimo da coluna)

`pd.to_datetime(df1['issue_responded']).dt.date.max()`:

Converte a coluna issue_responded para o tipo datetime e extrai a data (sem hora) da última resposta. (O valor máximo da coluna)

In [30]:
#avaliar o período de dados coletados desde o primeiro report até o último

data_do_report = pd.to_datetime(df1['Issue_reported at']).dt.date.min()

data_da_ultima_resposta_do_report = pd.to_datetime(df1['issue_responded']).dt.date.max()

print(f"o periodo de dados coletados vai de {data_do_report} até {data_da_ultima_resposta_do_report}")

o periodo de dados coletados vai de 2023-01-08 até 2023-12-08

# Informações de um DataFrame com `df1.info()`:

O método `df1.info()` é uma ferramenta do Pandas que fornece uma visão dos tipos de dados presentes em um DataFrame. Devemos analisar cada componente da saída para entender melhor as informações que ele fornece:

1. **Índice:**

Mostra o número de linhas no DataFrame.
Útil para verificar o tamanho do conjunto de dados.

2. **Colunas:**

Lista o nome de cada coluna no DataFrame.
Permite identificar as variáveis presentes no conjunto de dados.

3. **Tipos de dados:**

Indica o tipo de dados de cada coluna, como` int64` para números inteiros, `float64` para números de ponto flutuante, `object` para strings, etc.
Fundamental para entender como os dados são armazenados e para escolher as ferramentas de análise adequadas.

4. **Não nulos:**

Mostra o número de valores não nulos em cada coluna.
Útil para identificar colunas com muitos valores nulos que podem afetar a análise.

5. **Nulos:**

Indica o número de valores nulos em cada coluna.
Permite avaliar a quantidade de dados ausentes no conjunto de dados.

6. **Memória:**

Mostra a quantidade de memória utilizada pelo DataFrame.
Útil para avaliar o desempenho e a necessidade de otimização.

In [29]:
#informa os tipos de dados presentes na tabela
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85907 entries, 0 to 85906
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Unique id                85907 non-null  object
 1   channel_name             85907 non-null  object
 2   category                 85907 non-null  object
 3   Sub-category             85907 non-null  object
 4   Customer Remarks         28756 non-null  object
 5   Order_id                 67675 non-null  object
 6   order_date_time          17214 non-null  object
 7   Issue_reported at        85907 non-null  object
 8   issue_responded          85907 non-null  object
 9   Survey_response_Date     85907 non-null  object
 10  Customer_City            17079 non-null  object
 11  Product_category         17196 non-null  object
 12  Item_price               17206 non-null  float64
 13  connected_handling_time  242 non-null    float64
 14  Agent_name               85907 non-null  object
 15  Supervisor               85907 non-null  object
 16  Manager                  85907 non-null  object
 17  Tenure Bucket            85907 non-null  object
 18  Agent Shift              85907 non-null  object
 19  CSAT Score               85907 non-null  int64
dtypes: float64(2), int64(1), object(17)
memory usage: 13.1+ MB

# Análise de valores nulos com` df1.isnull().sum()`:

O código` df1.isnull().sum()` realiza uma análise detalhada dos valores nulos em um DataFrame do Pandas. Vamos explorar cada parte do código para entender seu funcionamento:

1. ` df1`: Representa o DataFrame que você deseja analisar.

2. `isnull()`: É um método do Pandas que retorna um DataFrame booleano com True para cada valor nulo e False para valores não nulos.

3. `sum()`: É um método do Pandas que soma os valores em cada coluna do DataFrame.

**Combinando esses métodos:**

`df1.isnull()`:

Retorna um DataFrame booleano com a localização dos valores nulos em df1.

`df1.isnull().sum()`:

Soma os valores True (nulos) em cada coluna do DataFrame booleano, retornando a quantidade de valores nulos em cada coluna.

In [7]:
#avalia se alguma variável posui valor nulo

df1.isnull().sum()

Unique id                      0
channel_name                   0
category                       0
Sub-category                   0
Customer Remarks           57151
Order_id                   18232
order_date_time            68693
Issue_reported at              0
issue_responded                0
Survey_response_Date           0
Customer_City              68828
Product_category           68711
Item_price                 68701
connected_handling_time    85665
Agent_name                     0
Supervisor                     0
Manager                        0
Tenure Bucket                  0
Agent Shift                    0
CSAT Score                     0
dtype: int64

# **Método -> describe ( )**

**Describe()** é um método em Pandas que calcula várias estatísticas descritivas para cada coluna numérica em um DataFrame. As estatísticas incluem contagem de valores não nulos, média, desvio padrão, mínimo, máximo e quartis.

In [8]:
round(df1.describe(),2)

       Item_price  connected_handling_time  CSAT Score
count    17206.00                   242.00    85907.00
mean      5660.77                   462.40        4.24
std      12825.73                   246.30        1.38
min          0.00                     0.00        1.00
25%        392.00                   293.00        4.00
50%        979.00                   427.00        5.00
75%       2699.75                   592.25        5.00
max     164999.00                  1986.00        5.00

# Média, Mediana e Moda

**Média**: A soma de todos os valores dividida pelo número de valores, representa o valor central da distribuição.

`.mean()`

---


**Mediana**: O valor que divide a lista ordenada em dois grupos com o mesmo número de elementos. Indica o "meio" da distribuição, não sendo influenciada por valores extremos.

`.median()`

---


**Moda**: O valor que aparece com mais frequência.

`.mode()`

In [9]:
#Valores maximos e minimos são autoexplicativos
valor_minimo= df1['Item_price'].min()
valor_maximo= df1['Item_price'].max()


media= df1['Item_price'].mean()
mediana= df1['Item_price'].median()
moda= df1['Item_price'].mode()
variancia= df1['Item_price'].var()

print(f' preço minimo: {valor_minimo},\n preço maximo:  {valor_maximo}')
print(f' media: {round(media,2)},\n mediana: {mediana}')
print(f' moda: {moda}')

 preço minimo: 0.0,
 preço maximo:  164999.0
 media: 5660.77,
 mediana: 979.0
 moda: 0    999.0
Name: Item_price, dtype: float64

# Variancia, Desvio Padrão e Quartis

**Variancia**:

A média dos quadrados das diferenças entre cada valor e a média, mede a dispersão dos dados em torno da média. O quão "espalhados" os dados estão em relação à média, captura a ideia da "distância média" de cada valor individual em relação ao valor central do conjunto de dados.

`.var( )`

---


**Desvio** **Padrão**:

A raiz quadrada da variância, indica a amplitude da dispersão dos dados.

O desvio padrão é útil para:

**Comparar conjuntos de dado**s: Se dois conjuntos de dados possuem a mesma média, o conjunto com o maior desvio padrão terá maior dispersão dos dados.

**Avaliar a confiabilidade da média**: Um desvio padrão alto indica que a média pode não ser um bom representante dos dados, pois muitos valores estão distantes dela.

**Identificar outliers**: Valores que se distanciam em mais de 3 desvios padrões da média podem ser considerados outliers.


(Outliers são valores que se distanciam significativamente do restante dos dados. Eles podem ser causados por erros de medição, valores atípicos ou características específicas da população. )

`.std( )`

---


**Quartis**:

Os quartis são valores que dividem um conjunto de dados ordenado em quatro partes iguais. Eles são úteis para entender a distribuição dos dados e identificar possíveis assimetrias. Os quartis fornecem uma visão geral da distribuição dos dados, indicando onde estão concentrados a maioria dos valores e se há assimetria.

*   Q1: 25% dos dados - Divide os dados em 4 partes iguais = `quantile.(0.25)`
*   Q2: 50% percentil - Mediana = `quantile.(0.5)`
*   Q3: 75% dos dados = `quantile.(0.75)`

Fornecem informações sobre a distribuição dos dados.


---




**Interquartil ou IQR**:

Diferença entre o Q3 e o Q1, mede a variabilidade central dos dados, excluindo outliers.  Ele é especialmente útil quando o conjunto de dados contém muitos outliers.

O IQR é menos influenciado por outliers do que outras medidas de dispersão, como a variância e o desvio padrão. Isso porque o IQR se concentra na metade central dos dados, ignorando os valores extremos.

In [10]:


variancia = df1['Item_price'].var()
desvio_padrao = df1['Item_price'].std()
Q1 = df1['Item_price'].quantile(0.25)
Q2 = df1['Item_price'].quantile(0.5)
Q3 = df1['Item_price'].quantile(0.75)
IQR = Q3 - Q1


print(f' variância: {round(variancia,2)}')
print(f' Desvio Padrão: {round(desvio_padrao,2)}')
print(f' Primeiro Quartil: {Q1}')
print(f' Segundo Quartil (mediana): {Q2}')
print(f' Terceiro Quartil: {Q3}')
print(f' Intervalo interquartil: {IQR} ')

 variância: 164499309.28
 Desvio Padrão: 12825.73
 Primeiro Quartil: 392.0
 Segundo Quartil (mediana): 979.0
 Terceiro Quartil: 2699.75
 Intervalo interquartil: 2307.75

# Assimetria e Curtose

**Assimetria(Skewness):**

A assimetria diz o quanto a distribuição dos dados está desbalanceada em torno da média. Indica se a maioria dos dados está concentrada em um lado da média ou se está distribuída de forma mais uniforme.

`.skew()`



---


Curtose:

A curtose é uma medida que complementa a assimetria, fornecendo informações sobre a forma das caudas da distribuição dos dados. Ela indica se as caudas são mais finas ou mais grossas do que em uma distribuição normal.

Curtose positiva (leptocúrtica): A curva é mais alta e fina do que a normal, com caudas mais longas e finas.

Curtose negativa (platicúrtica): A curva é mais baixa e achatada do que a normal, com caudas mais curtas e grossas.

Curtose zero (mesocúrtica): A curva é simétrica e em forma de sino, com caudas de tamanho normal.

A curtose pode influenciar a confiabilidade de intervalos de confiança, que são usados para estimar o valor real de uma população a partir de uma amostra.
Interpretação

(**As caudas** de uma distribuição de dados referem-se às extremidades da curva, onde os valores mais raros se concentram.)

`.kurtosis()`

In [11]:


assimetria = df1['Item_price'].skew()
curtose = df1['Item_price'].kurtosis()


print(f'Assimetria(Skewness): {round(assimetria,2)} ')
print(f'Curtose: {round(curtose,2)} ')

Assimetria(Skewness): 4.23
Curtose: 24.44

#Verificar o total de valores únicos de cada variável

O código itera pelas colunas do DataFrame df1 e calcula o número de valores únicos em cada coluna após convertê-las para strings. Em seguida, ele armazena essas contagens em uma lista chamada valores_unicos.


1.   Selecionando as primeiras 21 colunas (indexação baseada em 0) de `df1.columns`
2.   Convertendo as colunas selecionadas em uma lista usando `.tolist().`
3.   Percorrendo cada nome de coluna na lista usando o loop `for`

**`.columns`**: Este atributo do DataFrame acessa os nomes das colunas (rótulos) como uma sequência (como uma lista ou array).



---

# **Primeira parte do FOR :**


1. `print(i, ':', len(df1[i].astype(str).value_counts()))`

`i`: Representa o nome da coluna atual sendo iterada no loop (assumindo que está dentro de um loop iterando sobre df1.columns).

`df1[i]`: Seleciona uma coluna específica do DataFrame df_dados com base no nome da coluna i.

`.astype(str)`: Converte os dados na coluna selecionada para strings. Isso é necessário porque value_counts() geralmente funciona melhor com dados categóricos (strings ou categorias numéricas).

`.value_counts()`: Conta as ocorrências de cada valor único na coluna (agora contendo strings). Retorna uma série que mapeia cada valor único para sua frequência.

`len()`: Calcula o comprimento (número de elementos) da série retornada por value_counts(). Isso fornece o número de valores únicos na coluna após convertê-la para strings.


# **Segunda parte do FOR :**

2. `valores_unicos.append(len(df1[i].astype(str).value_counts()))`

`valores_unicos`: Destina-se a armazenar o número de valores únicos encontrados em cada coluna.

`.append()`: Adiciona um elemento ao final da lista valores_unicos.
O valor anexado é o mesmo resultado calculado na linha anterior. Isso armazena o número de valores únicos para cada coluna na lista valores_unicos.

In [ ]:
#Verificar o total de valores únicos de cada variável

valor_unico = []

for i in df1.columns[0:20].tolist():
  print(i, ':', len(df1[i].astype(str).value_counts()))
  valor_unico.append(len(df1[i].astype(str).value_counts()))

Unique id : 85907
channel_name : 3
category : 12
Sub-category : 57
Customer Remarks : 18233
Order_id : 67676
order_date_time : 13767
Issue_reported at : 30923
issue_responded : 30262
Survey_response_Date : 31
Customer_City : 1783
Product_category : 10
Item_price : 2790
connected_handling_time : 212
Agent_name : 1371
Supervisor : 40
Manager : 6
Tenure Bucket : 5
Agent Shift : 5
CSAT Score : 5

# Procurar valores acima de um numero "X" nas colunas

`df1.loc[ df1['Item price'] > x ].count() `:

Conta o número de linhas no DataFrame df1 onde o valor é superior a um valor X.


`df1.loc`: Acessa linhas específicas do DataFrame com base em uma condição booleana.

`df1['Item price'] > x`: Esta é a condição booleana que define quais linhas serão selecionadas. Ela verifica se o valor nas coluna é maior que um valor x.

`.count()`: Conta o número de linhas no DataFrame resultante após aplicar a condição booleana.

In [12]:
x = 8000
df1.loc[df1['Item_price'] > x ].count()

Unique id                  3070
channel_name               3070
category                   3070
Sub-category               3070
Customer Remarks           1085
Order_id                   3070
order_date_time            3070
Issue_reported at          3070
issue_responded            3070
Survey_response_Date       3070
Customer_City              3039
Product_category           3066
Item_price                 3070
connected_handling_time       1
Agent_name                 3070
Supervisor                 3070
Manager                    3070
Tenure Bucket              3070
Agent Shift                3070
CSAT Score                 3070
dtype: int64

In [16]:
df1.loc[df1['Item_price'] > x, 'Item_price']

19       15990.0
25       99999.0
37       11159.0
67       24999.0
68       15490.0
          ...
85762    67999.0
85774    25999.0
85805    25999.0
85859    11999.0
85901    23999.0
Name: Item_price, Length: 3070, dtype: float64

# Consultar a quantidade de registros


`.groupby(['channel_name']):`

groupby: É um método do Pandas usado para agrupar linhas em um DataFrame com base em uma ou mais colunas.O parâmetro `['channel_name']` define a coluna pela qual os dados serão agrupados. No exemplo, estamos agrupando por "channel_name", mas podemos usar outras colunas relevantes da tabela, como:


1. `['Agent shift'`]: para analisar o tempo de trabalho dos agentes;

2. `['Category'`]: para identificar as categorias mais frequentes;



> A escolha da coluna de agrupamento depende dos objetivos da sua análise. Diversas outras colunas da tabela podem ser utilizadas para agrupar os dados de maneira flexível.




`.size()`:  É um método aplicado ao resultado do groupby que conta o número de elementos em cada grupo.

Aplicações:

  1. Analisar a distribuição de dados por categoria.
  2. Identificar grupos com grande ou pouca quantidade de dados.
  3. Realizar cálculos estatísticos resumidos para cada grupo.

In [19]:
df1.groupby(['channel_name']).size()

channel_name
Email       3023
Inbound    68142
Outcall    14742
dtype: int64

In [20]:
df1.groupby(['Agent Shift']).size()

Agent Shift
Afternoon     5840
Evening      33677
Morning      41426
Night         1316
Split         3648
dtype: int64

In [22]:
df1.groupby(['category']).size()

category
App/website              84
Cancellation           2212
Feedback               2294
Offers & Cashback       480
Onboarding related       65
Order Related         23215
Others                   99
Payments related       2327
Product Queries        3692
Refund Related         4550
Returns               44097
Shopzilla Related      2792
dtype: int64